obj-m += mini2440_gpfxleds.o

all:

            make -C /lib/modules/ $(shell uname -r)/build M=$(PWD) modules

clean:

            make -C /lib/modules/ $(shell uname -r)/build M=$(PWD) clean